/*
 * ================================================================
 * 【第 14 課：預設建構函數（Default Constructor）】總複習 summary.cpp
 * ================================================================
 * 編譯方式：g++ -std=c++17 -o summary summary.cpp
 *
 * 本課重點：
 * 1. 預設建構函數的定義：不需要傳入任何參數就能調用的建構函數
 * 2. 編譯器自動生成的預設建構函數及其行為
 * 3. 預設建構函數消失的情況（定義了任何建構函數後）
 * 4. 解決方案：手動加回 vs = default（C++11）
 * 5. = default 與手動寫空建構函數的微妙差異（值初始化 / 平凡性）
 * 6. 帶預設參數的建構函數也算預設建構函數（及歧義陷阱）
 * 7. 預設建構函數與對象陣列的關係
 * 8. = delete：明確禁止預設建構（C++11）
 * ================================================================
 */

#include <iostream>
#include <string>
using namespace std;

// ================================================================
// 重點一：什麼是預設建構函數？
// ================================================================
// 預設建構函數 = 不需要傳入任何參數就能調用的建構函數
// 它有兩種形式：
//   形式 1：MyClass() { }                    // 無參數
//   形式 2：MyClass(int x = 0) { }          // 所有參數都有預設值
// 只要可以用 MyClass obj; 不帶任何參數創建對象，那就是預設建構函數。

// ================================================================
// 重點二：編譯器自動生成的預設建構函數
// ================================================================
// 如果完全沒有定義任何建構函數，編譯器會自動生成一個預設建構函數。
//
// ┌────────────────────────────────────┬────────────────────────┐
// │ 成員類型                           │ 自動生成的建構函數行為  │
// ├────────────────────────────────────┼────────────────────────┤
// │ 基本型別（int, double, float 等）  │ 不做任何初始化（垃圾值）│
// │ 類別型別（string, vector 等）      │ 調用該類別的預設建構函數│
// │ 陣列                               │ 按照上述規則處理每個元素│
// └────────────────────────────────────┴────────────────────────┘
// 符合 C++ 的「零開銷原則」：你沒要求初始化，就不花時間初始化。

class AutoGenerated {
public:
    int number;        // 基本型別 → 不會初始化（垃圾值）
    double value;      // 基本型別 → 不會初始化（垃圾值）
    string text;       // 類別型別 → 調用 string 的預設建構函數 → 空字串

    // 沒有定義任何建構函數 → 編譯器自動生成預設建構函數

    void print() const {
        cout << "  number = " << number << " (可能是垃圾值)" << endl;
        cout << "  value  = " << value << " (可能是垃圾值)" << endl;
        cout << "  text   = [" << text << "] (空字串)" << endl;
    }
};

// ================================================================
// 重點三：預設建構函數消失的情況
// ================================================================
// 規則：只要定義了「任何一個」建構函數（無論帶參還是不帶參），
//       編譯器就「不再自動生成」預設建構函數。
//
// 原因：編譯器的邏輯是——你既然自己定義了建構函數，
//       說明你有特殊的初始化需求，不應該擅自生成一個可能不符合意圖的預設建構函數。

class PointNoDefault {
public:
    int x, y;

    // 只定義了帶參數的建構函數
    PointNoDefault(int px, int py) {
        x = px;
        y = py;
    }
    // Point p;  → 編譯錯誤！沒有預設建構函數！
};

// ================================================================
// 重點四：解決方案
// ================================================================

// 方式一：手動寫一個無參數建構函數
class PointManual {
public:
    int x, y;

    PointManual() {
        x = 0;
        y = 0;
        cout << "  手動預設建構: Point(0, 0)" << endl;
    }

    PointManual(int px, int py) {
        x = px;
        y = py;
        cout << "  帶參建構: Point(" << x << ", " << y << ")" << endl;
    }
};

// 方式二（C++11）：使用 = default
class PointDefault {
public:
    int x, y;

    // 告訴編譯器：請幫我生成預設建構函數
    // 注意：x 和 y 仍然是未初始化的垃圾值（和自動生成的行為一樣）
    PointDefault() = default;

    PointDefault(int px, int py) {
        x = px;
        y = py;
    }
};

// ================================================================
// 重點五：= default 與手動寫空建構函數的微妙差異
// ================================================================
// 這是一個微妙但重要的區別，影響「值初始化」行為：
//
// ┌────────────────────┬───────────────────┬────────────────────┐
// │ 場景                │ = default          │ 手動寫 { }          │
// ├────────────────────┼───────────────────┼────────────────────┤
// │ A a; / B b;         │ 基本型別不初始化   │ 基本型別不初始化     │
// │ A a{}; / B b{};     │ 觸發值初始化，歸零 │ 只調用空建構，不歸零 │
// │ 語義                │ 平凡(trivial)建構  │ 使用者定義的建構     │
// └────────────────────┴───────────────────┴────────────────────┘
//
// = default 保留了「平凡性（triviality）」，
// 這讓類別可以享受某些編譯器優化（如 memcpy 優化、POD 類型判斷）。

class A_Default {
public:
    int value;
    A_Default() = default;  // 平凡建構函數
};

class B_UserDefined {
public:
    int value;
    B_UserDefined() { }     // 使用者定義的空建構函數
};

// ================================================================
// 重點六：帶預設參數的建構函數也是預設建構函數
// ================================================================
// 所有參數都有預設值 → 可以不帶參數調用 → 算預設建構函數
//
// 注意：不能同時有無參建構函數和全預設參數建構函數，否則會歧義！
//   class Bad {
//       Bad() { }              // 建構函數 A
//       Bad(int x = 0) { }    // 建構函數 B（也是預設建構函數）
//   };
//   Bad b;  // 編譯錯誤！歧義：應該調用 A 還是 B？

class Color {
private:
    int r, g, b;

public:
    // 所有參數都有預設值 → 這也是預設建構函數！
    Color(int red = 0, int green = 0, int blue = 0) {
        r = (red >= 0 && red <= 255) ? red : 0;
        g = (green >= 0 && green <= 255) ? green : 0;
        b = (blue >= 0 && blue <= 255) ? blue : 0;
    }

    void print() const {
        cout << "  RGB(" << r << ", " << g << ", " << b << ")" << endl;
    }
};

// ================================================================
// 重點七：預設建構函數與對象陣列
// ================================================================
// Enemy enemies[5]; → 要一次創建 5 個對象，
// 但語法上沒有位置讓你傳參數，所以每個元素都必須用預設建構函數初始化。
//
// 如果沒有預設建構函數：
//   NoDefault arr[3];  // 編譯錯誤！
//   解決方法：NoDefault arr[3] = { NoDefault(1), NoDefault(2), NoDefault(3) };

class Enemy {
private:
    string type;
    int health;

public:
    // 必須有預設建構函數，否則無法創建陣列
    Enemy() {
        type = "小怪";
        health = 100;
    }

    Enemy(string t, int hp) {
        type = t;
        health = hp;
    }

    void print() const {
        cout << "  " << type << " (HP: " << health << ")" << endl;
    }

    void setType(string t) { type = t; }
    void setHealth(int hp) { health = hp; }
};

// ================================================================
// 重點八：= delete 明確禁止預設建構（C++11）
// ================================================================
// 當對象在沒有特定資訊的情況下不應該存在時，
// 用 = delete 表達設計意圖。
// 比「忘記定義預設建構函數」更明確——
// 告訴閱讀程式碼的人：「我故意不允許預設建構。」

class DatabaseConnection {
private:
    string host;
    int port;

public:
    DatabaseConnection() = delete;  // 沒有連接資訊就不能創建

    DatabaseConnection(string h, int p) {
        host = h;
        port = p;
        cout << "  連接到 " << host << ":" << port << endl;
    }

    void print() const {
        cout << "  資料庫連接: " << host << ":" << port << endl;
    }
};

// ================================================================
// 綜合範例類別
// ================================================================

// 範例 1：使用 = default
class Config {
public:
    int width;
    int height;
    bool fullscreen;

    Config() = default;  // 請編譯器生成預設建構函數

    Config(int w, int h, bool fs)
        : width(w), height(h), fullscreen(fs) { }

    void print() const {
        cout << "  " << width << "x" << height
             << (fullscreen ? " [全螢幕]" : " [視窗]") << endl;
    }
};

// 範例 2：全預設參數的建構函數
class Timer {
private:
    int hours;
    int minutes;
    int seconds;

public:
    Timer(int h = 0, int m = 0, int s = 0) {
        hours = (h >= 0 && h < 24) ? h : 0;
        minutes = (m >= 0 && m < 60) ? m : 0;
        seconds = (s >= 0 && s < 60) ? s : 0;
    }

    void print() const {
        cout << "  ";
        if (hours < 10) cout << "0";
        cout << hours << ":";
        if (minutes < 10) cout << "0";
        cout << minutes << ":";
        if (seconds < 10) cout << "0";
        cout << seconds << endl;
    }
};

// 範例 3：= delete 禁止預設建構
class FileHandle {
private:
    string filename;
    bool isOpen;

public:
    FileHandle() = delete;  // 沒有檔名就不能創建

    FileHandle(string fname) {
        filename = fname;
        isOpen = true;
        cout << "  打開檔案: " << filename << endl;
    }

    void print() const {
        cout << "  檔案: " << filename
             << " [" << (isOpen ? "開啟" : "關閉") << "]" << endl;
    }
};

int main() {
    cout << "=================================================" << endl;
    cout << "   第 14 課：預設建構函數（Default Constructor）" << endl;
    cout << "=================================================" << endl;

    // --- 重點二：編譯器自動生成的預設建構函數 ---
    cout << "\n【1】編譯器自動生成的預設建構函數" << endl;
    AutoGenerated obj;
    obj.print();

    // --- 重點四：手動加回預設建構函數 ---
    cout << "\n【2】手動加回預設建構函數" << endl;
    PointManual pm1;           // 調用手動寫的預設建構函數
    PointManual pm2(3, 4);     // 調用帶參建構函數

    // --- 重點四：= default ---
    cout << "\n【3】使用 = default" << endl;
    PointDefault pd1;          // 使用編譯器生成的預設建構函數
    PointDefault pd2(5, 6);
    cout << "  pd1: x=" << pd1.x << ", y=" << pd1.y << " (可能是垃圾值)" << endl;
    cout << "  pd2: x=" << pd2.x << ", y=" << pd2.y << " (正確值)" << endl;

    // --- 重點五：= default 與手動空建構的差異 ---
    cout << "\n【4】= default vs 手動空建構（值初始化差異）" << endl;
    A_Default a1;       // value 是垃圾值
    B_UserDefined b1;   // value 也是垃圾值

    A_Default a2{};     // 值初始化：value 被歸零為 0！
    B_UserDefined b2{}; // 只調用空建構，不歸零

    cout << "  一般宣告：" << endl;
    cout << "    A_Default   a1.value = " << a1.value << " (垃圾值)" << endl;
    cout << "    B_UserDef   b1.value = " << b1.value << " (垃圾值)" << endl;
    cout << "  值初始化 {}：" << endl;
    cout << "    A_Default   a2.value = " << a2.value << " (應該是 0)" << endl;
    cout << "    B_UserDef   b2.value = " << b2.value << " (可能不是 0)" << endl;

    // --- 重點六：帶預設參數的建構函數 ---
    cout << "\n【5】帶預設參數的建構函數也是預設建構函數" << endl;
    Color c1;               // 全部使用預設值 → (0, 0, 0)
    Color c2(255);           // green 和 blue 用預設值 → (255, 0, 0)
    Color c3(0, 128);        // blue 用預設值 → (0, 128, 0)
    Color c4(100, 200, 50);  // 全部指定
    cout << "c1: "; c1.print();   // 黑色
    cout << "c2: "; c2.print();   // 紅色
    cout << "c3: "; c3.print();   // 綠色
    cout << "c4: "; c4.print();   // 自定義

    // --- 重點七：預設建構函數與對象陣列 ---
    cout << "\n【6】預設建構函數與對象陣列" << endl;
    Enemy enemies[5];  // 5 個 Enemy，每個都調用預設建構函數
    for (int i = 0; i < 5; i++) {
        enemies[i].print();
    }
    cout << "  修改後：" << endl;
    enemies[0].setType("Boss");
    enemies[0].setHealth(5000);
    enemies[0].print();

    // --- 重點八：= delete ---
    cout << "\n【7】= delete 禁止預設建構" << endl;
    // DatabaseConnection db;  // 編譯錯誤！預設建構函數被 delete
    DatabaseConnection db("localhost", 5432);
    db.print();

    // --- 綜合範例 ---
    cout << "\n【8】綜合範例" << endl;

    cout << "Config (= default):" << endl;
    Config cfg1{};                       // 值初始化：全部歸零
    Config cfg2(1920, 1080, true);       // 帶參建構
    cout << "cfg1: "; cfg1.print();
    cout << "cfg2: "; cfg2.print();

    cout << "Timer (全預設參數):" << endl;
    Timer t1;                // 全部預設 → 00:00:00
    Timer t2(14);            // 只給小時 → 14:00:00
    Timer t3(8, 30);         // 給小時和分鐘 → 08:30:00
    Timer t4(23, 59, 59);   // 全部指定
    cout << "t1: "; t1.print();
    cout << "t2: "; t2.print();
    cout << "t3: "; t3.print();
    cout << "t4: "; t4.print();

    cout << "FileHandle (= delete):" << endl;
    // FileHandle fh;  // 編譯錯誤！
    FileHandle f1("data.txt");
    FileHandle f2("config.json");
    f1.print();
    f2.print();

    // --- 重點回顧 ---
    cout << "\n=================================================" << endl;
    cout << "本課重點回顧：" << endl;
    cout << "  1. 預設建構函數 = 不需要參數就能調用的建構函數" << endl;
    cout << "  2. 完全沒定義建構函數時，編譯器才會自動生成" << endl;
    cout << "  3. 自動生成的不初始化基本型別，但會調用類別型別的建構函數" << endl;
    cout << "  4. = default：明確要求編譯器生成，保留平凡性(triviality)" << endl;
    cout << "  5. = delete：明確禁止預設建構函數" << endl;
    cout << "  6. 全預設參數的建構函數也算預設建構函數（注意歧義）" << endl;
    cout << "  7. 對象陣列 T arr[N]; 需要預設建構函數" << endl;
    cout << "  8. T obj{}; 配合 = default 會將基本型別歸零（值初始化）" << endl;
    cout << "=================================================" << endl;

    return 0;
}
