/*
好的，信安！讓我們繼續。

---

# 第 14 課：預設建構函數（Default Constructor）

---

## 14.1 什麼是預設建構函數？

預設建構函數（Default Constructor）是指**不需要傳入任何參數就能調用的建構函數**。它有兩種形式：

```cpp
class MyClass {
public:
    MyClass() { }                    // 形式 1：無參數
    MyClass(int x = 0) { }          // 形式 2：所有參數都有預設值（也算預設建構函數）
};
```

只要可以用 `MyClass obj;` 這種方式（不帶任何參數）創建對象，那個被調用的建構函數就是預設建構函數。

---

## 14.2 編譯器自動生成的預設建構函數

如果你**完全沒有定義任何建構函數**，編譯器會幫你自動生成一個預設建構函數。我們來觀察它的行為：

```cpp
#include <iostream>
#include <string>
using namespace std;

class AutoGenerated {
public:
    int number;        // 基本型別
    double value;      // 基本型別
    string text;       // 類別型別（string 有自己的預設建構函數）
    
    // 我們沒有定義任何建構函數
    // 編譯器會自動生成一個預設建構函數
    
    void print() const {
        cout << "number = " << number << endl;   // 未定義（垃圾值）
        cout << "value  = " << value << endl;    // 未定義（垃圾值）
        cout << "text   = [" << text << "]" << endl;  // 空字串（string 的預設建構）
    }
};

int main() {
    cout << "=== 編譯器自動生成的預設建構函數 ===" << endl;
    AutoGenerated obj;
    obj.print();
    
    return 0;
}
```

### 預期輸出（垃圾值每次不同）

```
=== 編譯器自動生成的預設建構函數 ===
number = 32764
value  = 6.95322e-310
text   = []
```

### 編譯器生成的預設建構函數做了什麼？

| 成員類型 | 行為 |
|----------|------|
| 基本型別（int、double、float、char、bool、指標等） | **不做任何初始化**，保持垃圾值 |
| 類別型別（string、vector 等） | **調用該類別自己的預設建構函數** |
| 陣列 | 對陣列中的每個元素按照上面的規則處理 |

**關鍵理解**：編譯器自動生成的預設建構函數**不是什麼都不做**，它會負責調用類別型別成員的建構函數；但它**不會初始化基本型別成員**。這完全符合 C++ 的「零開銷原則」——你沒要求初始化，就不花時間初始化。

---

## 14.3 預設建構函數消失的情況

這是第 13 課提到的重要概念，現在我們深入理解：

```cpp
#include <iostream>
using namespace std;

class Point {
public:
    int x, y;
    
    // 只定義了帶參數的建構函數
    Point(int px, int py) {
        x = px;
        y = py;
        cout << "Point(" << x << ", " << y << ") 建構完成" << endl;
    }
};

int main() {
    Point p1(3, 4);    // OK：匹配帶參建構函數
    
    // Point p2;        // 編譯錯誤！
    // error: no matching function for call to 'Point::Point()'
    
    // Point p3{};      // 編譯錯誤！同樣需要預設建構函數
    
    return 0;
}
```

**規則**：只要你定義了**任何一個**建構函數（無論是帶參還是不帶參），編譯器就**不再自動生成**預設建構函數。

為什麼要這樣設計？因為編譯器的邏輯是：「你既然自己定義了建構函數，說明你有特殊的初始化需求，我不應該擅自幫你生成一個可能不符合你意圖的預設建構函數。」

---

## 14.4 解決方案：手動加回預設建構函數

### 方式一：自己寫一個無參數建構函數

```cpp
#include <iostream>
using namespace std;

class Point {
public:
    int x, y;
    
    // 手動加回預設建構函數
    Point() {
        x = 0;
        y = 0;
        cout << "預設建構: Point(0, 0)" << endl;
    }
    
    Point(int px, int py) {
        x = px;
        y = py;
        cout << "帶參建構: Point(" << x << ", " << y << ")" << endl;
    }
};

int main() {
    Point p1;          // OK：調用預設建構函數
    Point p2(3, 4);    // OK：調用帶參建構函數
    return 0;
}
```

### 方式二（C++11）：使用 `= default`

```cpp
#include <iostream>
using namespace std;

class Point {
public:
    int x, y;
    
    // 告訴編譯器：請幫我生成預設建構函數
    Point() = default;
    
    Point(int px, int py) {
        x = px;
        y = py;
        cout << "帶參建構: Point(" << x << ", " << y << ")" << endl;
    }
};

int main() {
    Point p1;          // OK：使用編譯器生成的預設建構函數
    Point p2(3, 4);    // OK
    
    // 注意：p1.x 和 p1.y 仍然是未初始化的垃圾值！
    // 因為 = default 生成的建構函數和編譯器原本自動生成的行為一樣
    cout << "p1.x = " << p1.x << ", p1.y = " << p1.y << endl;  // 垃圾值
    
    return 0;
}
```

---

## 14.5 `= default` 與手動寫空建構函數的差異

這是一個微妙但重要的區別：

```cpp
#include <iostream>
using namespace std;

class A {
public:
    int value;
    A() = default;  // 編譯器生成的版本
};

class B {
public:
    int value;
    B() { }  // 使用者自己寫的空建構函數
};

int main() {
    // === 情境 1：一般宣告 ===
    A a1;    // value 是垃圾值（= default 不初始化基本型別）
    B b1;    // value 也是垃圾值（空建構函數也不初始化）
    
    // === 情境 2：值初始化（Value Initialization）===
    A a2{};  // value 被初始化為 0！
    B b2{};  // value 仍然是垃圾值！
    
    cout << "=== 一般宣告 ===" << endl;
    cout << "a1.value = " << a1.value << " (垃圾值)" << endl;
    cout << "b1.value = " << b1.value << " (垃圾值)" << endl;
    
    cout << "\n=== 值初始化 {} ===" << endl;
    cout << "a2.value = " << a2.value << " (應該是 0)" << endl;
    cout << "b2.value = " << b2.value << " (可能仍是垃圾值)" << endl;
    
    return 0;
}
```

### 預期輸出

```
=== 一般宣告 ===
a1.value = 32764 (垃圾值)
b1.value = 0 (垃圾值)

=== 值初始化 {} ===
a2.value = 0 (應該是 0)
b2.value = 0 (可能仍是垃圾值)
```

**差異解析**：

| 場景 | `= default` | 手動寫 `{ }` |
|------|-------------|--------------|
| `A a;` / `B b;` | 基本型別不初始化 | 基本型別不初始化 |
| `A a{};` / `B b{};` | **觸發值初始化**，基本型別歸零 | 只調用空建構函數，**不觸發值初始化** |
| 語義 | 這是一個**平凡的（trivial）**建構函數 | 這是一個**使用者定義的**建構函數 |

`= default` 保留了建構函數的「平凡性（triviality）」，這讓類別可以享受某些編譯器優化，也影響了值初始化的行為。這在進階場景（例如 `memcpy` 優化、POD 類型判斷）中很重要。

---

## 14.6 帶預設參數的建構函數也是預設建構函數

```cpp
#include <iostream>
using namespace std;

class Color {
private:
    int r, g, b;

public:
    // 所有參數都有預設值 → 這也是預設建構函數！
    Color(int red = 0, int green = 0, int blue = 0) {
        r = (red >= 0 && red <= 255) ? red : 0;
        g = (green >= 0 && green <= 255) ? green : 0;
        b = (blue >= 0 && blue <= 255) ? blue : 0;
    }

    void print() const {
        cout << "  RGB(" << r << ", " << g << ", " << b << ")" << endl;
    }
};

int main() {
    Color c1;               // 全部使用預設值 → (0, 0, 0)
    Color c2(255);           // green 和 blue 用預設值 → (255, 0, 0)
    Color c3(0, 128);        // blue 用預設值 → (0, 128, 0)
    Color c4(100, 200, 50);  // 全部指定
    
    cout << "c1: "; c1.print();   // 黑色
    cout << "c2: "; c2.print();   // 紅色
    cout << "c3: "; c3.print();   // 綠色
    cout << "c4: "; c4.print();   // 自定義
    
    return 0;
}
```

### 預期輸出

```
c1:   RGB(0, 0, 0)
c2:   RGB(255, 0, 0)
c3:   RGB(0, 128, 0)
c4:   RGB(100, 200, 50)
```

但要注意，**不能同時有無參建構函數和全預設參數建構函數**，否則會產生歧義：

```cpp
class Bad {
public:
    Bad() { }                    // 建構函數 A
    Bad(int x = 0) { }          // 建構函數 B（也是預設建構函數）
};

int main() {
    Bad b;  // 編譯錯誤！歧義：應該調用 A 還是 B？
    return 0;
}
```

---

## 14.7 預設建構函數與陣列

預設建構函數在使用**對象陣列**時非常重要：

```cpp
#include <iostream>
#include <string>
using namespace std;

class Enemy {
private:
    string type;
    int health;

public:
    // 必須有預設建構函數，否則無法創建陣列
    Enemy() {
        type = "小怪";
        health = 100;
    }
    
    Enemy(string t, int hp) {
        type = t;
        health = hp;
    }

    void print() const {
        cout << "  " << type << " (HP: " << health << ")" << endl;
    }
    
    void setType(string t) { type = t; }
    void setHealth(int hp) { health = hp; }
};

int main() {
    cout << "=== 對象陣列（需要預設建構函數）===" << endl;
    
    // 創建 5 個 Enemy，每個都調用預設建構函數
    Enemy enemies[5];
    
    for (int i = 0; i < 5; i++) {
        enemies[i].print();
    }
    
    cout << "\n=== 修改後 ===" << endl;
    enemies[0].setType("Boss");
    enemies[0].setHealth(5000);
    enemies[2].setType("精英怪");
    enemies[2].setHealth(500);
    
    for (int i = 0; i < 5; i++) {
        enemies[i].print();
    }
    
    return 0;
}
```

### 預期輸出

```
=== 對象陣列（需要預設建構函數）===
  小怪 (HP: 100)
  小怪 (HP: 100)
  小怪 (HP: 100)
  小怪 (HP: 100)
  小怪 (HP: 100)

=== 修改後 ===
  Boss (HP: 5000)
  小怪 (HP: 100)
  精英怪 (HP: 500)
  小怪 (HP: 100)
  小怪 (HP: 100)
```

**為什麼需要預設建構函數？** 因為 `Enemy enemies[5];` 要一次創建 5 個對象，但語法上沒有位置讓你傳參數給每一個元素，所以每個元素都必須用預設建構函數來初始化。

如果沒有預設建構函數：

```cpp
class NoDefault {
public:
    NoDefault(int x) { }  // 只有帶參建構函數
};

int main() {
    // NoDefault arr[3];   // 編譯錯誤！沒有預設建構函數！
    
    // 解決方法：用初始化列表逐一初始化
    NoDefault arr[3] = { NoDefault(1), NoDefault(2), NoDefault(3) };  // OK
    return 0;
}
```

---

## 14.8 `= delete`：明確禁止預設建構

有時候你**故意不想**讓對象在沒有參數的情況下被創建，可以用 `= delete`（C++11）：

```cpp
#include <iostream>
#include <string>
using namespace std;

class DatabaseConnection {
private:
    string host;
    int port;

public:
    // 明確禁止預設建構：沒有連接資訊就不能創建
    DatabaseConnection() = delete;
    
    DatabaseConnection(string h, int p) {
        host = h;
        port = p;
        cout << "連接到 " << host << ":" << port << endl;
    }

    void print() const {
        cout << "  資料庫連接: " << host << ":" << port << endl;
    }
};

int main() {
    // DatabaseConnection db;  // 編譯錯誤！預設建構函數被 delete 了
    // error: use of deleted function 'DatabaseConnection::DatabaseConnection()'
    
    DatabaseConnection db("localhost", 5432);  // OK
    db.print();
    
    return 0;
}
```

### 預期輸出

```
連接到 localhost:5432
  資料庫連接: localhost:5432
```

**使用場景**：當一個對象在沒有特定資訊的情況下不應該存在時，用 `= delete` 表達你的設計意圖。這比「忘記定義預設建構函數」更明確——它告訴閱讀程式碼的人：「我**故意**不允許預設建構。」

---

## 14.9 完整綜合範例

```cpp
#include <iostream>
#include <string>
using namespace std;

// ============================================================
// 範例 1：使用 = default
// ============================================================
class Config {
public:
    int width;
    int height;
    bool fullscreen;
    
    Config() = default;  // 請編譯器生成預設建構函數
    
    Config(int w, int h, bool fs) 
        : width(w), height(h), fullscreen(fs) { }
    
    void print() const {
        cout << "  " << width << "x" << height 
             << (fullscreen ? " [全螢幕]" : " [視窗]") << endl;
    }
};

// ============================================================
// 範例 2：全預設參數的建構函數
// ============================================================
class Timer {
private:
    int hours;
    int minutes;
    int seconds;

public:
    Timer(int h = 0, int m = 0, int s = 0) {
        hours = (h >= 0 && h < 24) ? h : 0;
        minutes = (m >= 0 && m < 60) ? m : 0;
        seconds = (s >= 0 && s < 60) ? s : 0;
    }
    
    void print() const {
        // 手動格式化為 HH:MM:SS
        cout << "  ";
        if (hours < 10) cout << "0";
        cout << hours << ":";
        if (minutes < 10) cout << "0";
        cout << minutes << ":";
        if (seconds < 10) cout << "0";
        cout << seconds << endl;
    }
};

// ============================================================
// 範例 3：= delete 禁止預設建構
// ============================================================
class FileHandle {
private:
    string filename;
    bool isOpen;

public:
    FileHandle() = delete;  // 沒有檔名就不能創建
    
    FileHandle(string fname) {
        filename = fname;
        isOpen = true;
        cout << "  打開檔案: " << filename << endl;
    }
    
    void print() const {
        cout << "  檔案: " << filename 
             << " [" << (isOpen ? "開啟" : "關閉") << "]" << endl;
    }
};

int main() {
    cout << "========================================" << endl;
    cout << "   第 14 課：預設建構函數 綜合範例" << endl;
    cout << "========================================" << endl;
    
    // --- Config：= default ---
    cout << "\n[1] Config (= default)" << endl;
    Config c1{};                         // 值初始化：全部歸零
    Config c2(1920, 1080, true);         // 帶參建構
    cout << "c1: "; c1.print();
    cout << "c2: "; c2.print();
    
    // --- Timer：全預設參數 ---
    cout << "\n[2] Timer (全預設參數)" << endl;
    Timer t1;                // 全部預設 → 00:00:00
    Timer t2(14);            // 只給小時 → 14:00:00
    Timer t3(8, 30);         // 給小時和分鐘 → 08:30:00
    Timer t4(23, 59, 59);   // 全部指定
    cout << "t1: "; t1.print();
    cout << "t2: "; t2.print();
    cout << "t3: "; t3.print();
    cout << "t4: "; t4.print();
    
    // --- Timer 陣列（因為有預設建構函數，所以可以） ---
    cout << "\n[3] Timer 陣列" << endl;
    Timer timers[3];  // 3 個 Timer 都用預設值
    for (int i = 0; i < 3; i++) {
        cout << "timers[" << i << "]: ";
        timers[i].print();
    }
    
    // --- FileHandle：= delete ---
    cout << "\n[4] FileHandle (= delete)" << endl;
    // FileHandle fh;  // 編譯錯誤！
    FileHandle f1("data.txt");
    FileHandle f2("config.json");
    f1.print();
    f2.print();
    
    return 0;
}
```

### 編譯與執行

```bash
g++ -std=c++17 -o lesson14 lesson14.cpp
./lesson14
```

### 預期輸出

```
========================================
   第 14 課：預設建構函數 綜合範例
========================================

[1] Config (= default)
c1:   0x0 [視窗]
c2:   1920x1080 [全螢幕]

[2] Timer (全預設參數)
t1:   00:00:00
t2:   14:00:00
t3:   08:30:00
t4:   23:59:59

[3] Timer 陣列
timers[0]:   00:00:00
timers[1]:   00:00:00
timers[2]:   00:00:00

[4] FileHandle (= delete)
  打開檔案: data.txt
  打開檔案: config.json
  檔案: data.txt [開啟]
  檔案: config.json [開啟]
```

---

## 14.10 本課重點回顧

| 概念 | 說明 |
|------|------|
| 預設建構函數 | 不需要參數就能調用的建構函數 |
| 編譯器自動生成 | 只有在你**完全沒有定義任何建構函數**時才會自動生成 |
| 自動生成的行為 | 不初始化基本型別，但會調用類別型別成員的建構函數 |
| `= default` | 明確要求編譯器生成預設建構函數，保留平凡性 |
| `= delete` | 明確禁止預設建構函數 |
| 全預設參數 | 所有參數都有預設值的建構函數也算預設建構函數 |
| 陣列需求 | 對象陣列 `T arr[N];` 需要預設建構函數 |
| 值初始化 | `T obj{};` 配合 `= default` 會將基本型別歸零 |

---

## 14.11 下一課預告

下一課我們將學習**帶參數的建構函數**的更多細節——包括參數傳遞方式的選擇（值傳遞 vs 引用傳遞 vs const 引用）、參數命名與成員同名的處理、以及預設參數的進階用法。

準備好進入 **第 15 課：帶參數的建構函數** 了嗎？
*/



#include <iostream>
#include <string>
using namespace std;

// ============================================================
// 範例 1：使用 = default
// ============================================================
class Config {
public:
    int width;
    int height;
    bool fullscreen;
    
    Config() = default;  // 請編譯器生成預設建構函數
    
    Config(int w, int h, bool fs) 
        : width(w), height(h), fullscreen(fs) { }
    
    void print() const {
        cout << "  " << width << "x" << height 
             << (fullscreen ? " [全螢幕]" : " [視窗]") << endl;
    }
};

// ============================================================
// 範例 2：全預設參數的建構函數
// ============================================================
class Timer {
private:
    int hours;
    int minutes;
    int seconds;

public:
    Timer(int h = 0, int m = 0, int s = 0) {
        hours = (h >= 0 && h < 24) ? h : 0;
        minutes = (m >= 0 && m < 60) ? m : 0;
        seconds = (s >= 0 && s < 60) ? s : 0;
    }
    
    void print() const {
        // 手動格式化為 HH:MM:SS
        cout << "  ";
        if (hours < 10) cout << "0";
        cout << hours << ":";
        if (minutes < 10) cout << "0";
        cout << minutes << ":";
        if (seconds < 10) cout << "0";
        cout << seconds << endl;
    }
};

// ============================================================
// 範例 3：= delete 禁止預設建構
// ============================================================
class FileHandle {
private:
    string filename;
    bool isOpen;

public:
    FileHandle() = delete;  // 沒有檔名就不能創建
    
    FileHandle(string fname) {
        filename = fname;
        isOpen = true;
        cout << "  打開檔案: " << filename << endl;
    }
    
    void print() const {
        cout << "  檔案: " << filename 
             << " [" << (isOpen ? "開啟" : "關閉") << "]" << endl;
    }
};

int main() {
    cout << "========================================" << endl;
    cout << "   第 14 課：預設建構函數 綜合範例" << endl;
    cout << "========================================" << endl;
    
    // --- Config：= default ---
    cout << "\n[1] Config (= default)" << endl;
    Config c1{};                         // 值初始化：全部歸零
    Config c2(1920, 1080, true);         // 帶參建構
    cout << "c1: "; c1.print();
    cout << "c2: "; c2.print();
    
    // --- Timer：全預設參數 ---
    cout << "\n[2] Timer (全預設參數)" << endl;
    Timer t1;                // 全部預設 → 00:00:00
    Timer t2(14);            // 只給小時 → 14:00:00
    Timer t3(8, 30);         // 給小時和分鐘 → 08:30:00
    Timer t4(23, 59, 59);   // 全部指定
    cout << "t1: "; t1.print();
    cout << "t2: "; t2.print();
    cout << "t3: "; t3.print();
    cout << "t4: "; t4.print();
    
    // --- Timer 陣列（因為有預設建構函數，所以可以） ---
    cout << "\n[3] Timer 陣列" << endl;
    Timer timers[3];  // 3 個 Timer 都用預設值
    for (int i = 0; i < 3; i++) {
        cout << "timers[" << i << "]: ";
        timers[i].print();
    }
    
    // --- FileHandle：= delete ---
    cout << "\n[4] FileHandle (= delete)" << endl;
    // FileHandle fh;  // 編譯錯誤！
    FileHandle f1("data.txt");
    FileHandle f2("config.json");
    f1.print();
    f2.print();
    
    return 0;
}
