// =============================================================================
//  第 14 課：預設建構函數 10  —  綜合實戰：= default / 全預設參數 / = delete
// =============================================================================
//
// 【主題資訊 Information】
//   主題：本課完整講義 + 三種控制預設建構函式的手法各出一個可執行範例
//   標準版本：`= default` 與 `= delete` 需 C++11；全預設參數 C++98 起即可
//   標頭檔：<string>、<vector>
//   本檔結構：① 下方大段課程講義（markdown）② 三個對照範例 Config / Timer / FileHandle
//
// 【詳細解釋 Explanation】
//
// 【1. 三個範例分別代表三種設計決策】
//   * Config   → `= default`：「我要編譯器原本的行為，只是它被我的帶參版本擠掉了」
//   * Timer    → 全預設參數：「一個建構函式同時涵蓋 0~3 個引數的所有情況」
//   * FileHandle → `= delete`：「沒有檔名的檔案 handle 沒有意義，禁止建立」
//   選哪一種取決於「無參建立這件事在語意上成不成立」，而不是哪個寫起來方便。
//
// 【2. Config 用 `= default` 的隱藏風險】
//   `Config() = default;` 不會初始化 width/height/fullscreen ——
//   它就是編譯器原本的行為，對內建型別什麼都不做。
//   所以 `Config c1;` 之後讀取 c1.width 是 undefined behavior。
//   本檔在講義的範例中示範了這個現象，實際輸出請看檔尾的注意事項。
//   若要「既保留 `= default` 又保證有初值」，正解是搭配 NSDMI：
//       int width = 800;  int height = 600;  bool fullscreen = false;
//       Config() = default;
//   本檔新增的 ConfigSafe 即是此寫法，兩者可直接對照。
//
// 【3. Timer 的全預設參數：一個函式扮演四種角色】
//   `Timer(int h = 0, int m = 0, int s = 0)` 同時是預設建構函式與帶參建構函式。
//   注意它不能再多寫一個 `Timer()` —— 兩者對 `Timer t;` 都可行，會產生歧義。
//   它的驗證策略是「超出範圍就歸零」，與第 6 檔的 Color 相同，
//   同樣有「25 點變成 0 點」這種不易察覺的問題；本檔在 TimerSafe 中改用 clamp 對照。
//
// 【4. FileHandle 用 `= delete` 的理由】
//   一個沒有檔名的檔案 handle 是「合法存在但沒有意義」的東西。
//   允許它存在的代價是：後續每個使用點都得先檢查「這個 handle 有效嗎」。
//   用 `= delete` 把它在編譯期消滅，等於用型別系統宣告
//   「拿到 FileHandle 就一定綁定了某個檔案」——後續程式碼因此變乾淨。
//
// 【概念補充 Concept Deep Dive】
//   * 這三種手法可以組合：實務上很常見的是
//     「`= delete` 預設建構 + `= delete` 複製 + 提供移動建構」，
//     這正是 unique_ptr、fstream、lock_guard 這類 RAII 型別的標準形狀。
//   * `= default` 與手寫 `{}` 在值初始化時行為不同（見第 5 檔），
//     這是本課最容易被面試問到的細節。
//   * 「全預設參數的建構函式也是預設建構函式」是標準定義的直接推論：
//     預設建構函式的定義是「不需要引數就能呼叫」，不是「參數列為空」。
//
// 【注意事項 Pay Attention】
//   1. `= default` 不會初始化內建型別成員 —— 要保證初值請搭配 NSDMI。
//   2. 全預設參數的建構函式不可與無參建構函式並存（歧義）。
//   3. `= delete` 之後，該型別就不能用於需要預設建構的容器用法
//      （`vector<T> v(n)`、`T arr[n]`），請改用 emplace_back。
//
// ═══════════════════════════════════════════════════════════════════════════
// 【面試題】預設建構函數綜合
// ───────────────────────────────────────────────────────────────────────────
// 🔥 Q1. 讓一個「已經有帶參建構函式」的類別重新支援無參建立，有哪些做法？
//     答：三種：① 手寫一個無參建構函式（可自訂初值）；
//         ② `X() = default;`（要編譯器原本的行為，通常搭配 NSDMI）；
//         ③ 讓帶參版本的所有參數都有預設值（一個函式涵蓋所有情況）。
//         第三種不能再另外寫 `X()`，否則 `X x;` 會歧義。
//     追問：三者怎麼選？→ 要自訂初值用 ①；只要編譯器行為用 ②＋NSDMI；
//           參數本來就有合理預設值時 ③ 最簡潔。
//
// 🔥 Q2. `Config() = default;` 之後，`Config c; cout << c.width;` 安全嗎？
//     答：不安全。`= default` 就是編譯器原本的行為 —— 對 int/bool 什麼都不做，
//         所以 width 的值不確定，讀取它是 undefined behavior。
//         要保證有初值必須搭配 NSDMI（`int width = 800;`）。
//     追問：那 `Config c{};` 呢？→ 這個安全。因為 `Config()` 非 user-provided，
//           值初始化會先零初始化整個物件。但這要靠呼叫端記得寫大括號，
//           類別作者無法強制，所以 NSDMI 仍是更可靠的做法。
//
// 🔥 Q3. 什麼時候該用 `= delete` 而不是「乾脆不寫」？
//     答：當「不可無參建立」是刻意的設計決策時。兩者都會讓編譯失敗，
//         但 `= delete` 讓錯誤訊息變成明確的 "use of deleted function"，
//         並把設計意圖寫進程式碼，日後維護者不會誤以為是漏寫。
//     追問：deleted 函式還有什麼妙用？→ 因為它仍參與多載解析，
//           可以用 `void f(char) = delete;` 精準攔截「型別對但語意錯」的呼叫。
//
// ⚠️ 陷阱. 下面這樣寫為什麼編譯不過？
//         class Timer {
//         public:
//             Timer() { }
//             Timer(int h = 0, int m = 0, int s = 0) { }
//         };
//         Timer t;
//     答：兩個建構函式都能以「不提供任何引數」的方式被呼叫，
//         overload resolution 找不到唯一最佳解 → ambiguous，編譯錯誤。
//     為什麼會錯：以為「無參版本」與「全預設參數版本」是不同的兩個函式，
//         可以共存。實際上判斷歧義看的是「這個呼叫式能匹配幾個候選」，
//         而 `Timer t;` 對兩者都成立。一個類別最多只能有一個可無引數呼叫的建構函式。
// ═══════════════════════════════════════════════════════════════════════════

/*
好的，信安！讓我們繼續。

---

# 第 14 課：預設建構函數（Default Constructor）

---

## 14.1 什麼是預設建構函數？

預設建構函數（Default Constructor）是指**不需要傳入任何參數就能調用的建構函數**。它有兩種形式：

```cpp
class MyClass {
public:
    MyClass() { }                    // 形式 1：無參數
    MyClass(int x = 0) { }          // 形式 2：所有參數都有預設值（也算預設建構函數）
};
```

只要可以用 `MyClass obj;` 這種方式（不帶任何參數）創建對象，那個被調用的建構函數就是預設建構函數。

---

## 14.2 編譯器自動生成的預設建構函數

如果你**完全沒有定義任何建構函數**，編譯器會幫你自動生成一個預設建構函數。我們來觀察它的行為：

```cpp
#include <iostream>
#include <string>
using namespace std;

class AutoGenerated {
public:
    int number;        // 基本型別
    double value;      // 基本型別
    string text;       // 類別型別（string 有自己的預設建構函數）
    
    // 我們沒有定義任何建構函數
    // 編譯器會自動生成一個預設建構函數
    
    void print() const {
        cout << "number = " << number << endl;   // 未定義（垃圾值）
        cout << "value  = " << value << endl;    // 未定義（垃圾值）
        cout << "text   = [" << text << "]" << endl;  // 空字串（string 的預設建構）
    }
};

int main() {
    cout << "=== 編譯器自動生成的預設建構函數 ===" << endl;
    AutoGenerated obj;
    obj.print();
    
    return 0;
}
```

### 預期輸出（垃圾值每次不同）

```
=== 編譯器自動生成的預設建構函數 ===
number = 32764
value  = 6.95322e-310
text   = []
```

### 編譯器生成的預設建構函數做了什麼？

| 成員類型 | 行為 |
|----------|------|
| 基本型別（int、double、float、char、bool、指標等） | **不做任何初始化**，保持垃圾值 |
| 類別型別（string、vector 等） | **調用該類別自己的預設建構函數** |
| 陣列 | 對陣列中的每個元素按照上面的規則處理 |

**關鍵理解**：編譯器自動生成的預設建構函數**不是什麼都不做**，它會負責調用類別型別成員的建構函數；但它**不會初始化基本型別成員**。這完全符合 C++ 的「零開銷原則」——你沒要求初始化，就不花時間初始化。

---

## 14.3 預設建構函數消失的情況

這是第 13 課提到的重要概念，現在我們深入理解：

```cpp
#include <iostream>
using namespace std;

class Point {
public:
    int x, y;
    
    // 只定義了帶參數的建構函數
    Point(int px, int py) {
        x = px;
        y = py;
        cout << "Point(" << x << ", " << y << ") 建構完成" << endl;
    }
};

int main() {
    Point p1(3, 4);    // OK：匹配帶參建構函數
    
    // Point p2;        // 編譯錯誤！
    // error: no matching function for call to 'Point::Point()'
    
    // Point p3{};      // 編譯錯誤！同樣需要預設建構函數
    
    return 0;
}
```

**規則**：只要你定義了**任何一個**建構函數（無論是帶參還是不帶參），編譯器就**不再自動生成**預設建構函數。

為什麼要這樣設計？因為編譯器的邏輯是：「你既然自己定義了建構函數，說明你有特殊的初始化需求，我不應該擅自幫你生成一個可能不符合你意圖的預設建構函數。」

---

## 14.4 解決方案：手動加回預設建構函數

### 方式一：自己寫一個無參數建構函數

```cpp
#include <iostream>
using namespace std;

class Point {
public:
    int x, y;
    
    // 手動加回預設建構函數
    Point() {
        x = 0;
        y = 0;
        cout << "預設建構: Point(0, 0)" << endl;
    }
    
    Point(int px, int py) {
        x = px;
        y = py;
        cout << "帶參建構: Point(" << x << ", " << y << ")" << endl;
    }
};

int main() {
    Point p1;          // OK：調用預設建構函數
    Point p2(3, 4);    // OK：調用帶參建構函數
    return 0;
}
```

### 方式二（C++11）：使用 `= default`

```cpp
#include <iostream>
using namespace std;

class Point {
public:
    int x, y;
    
    // 告訴編譯器：請幫我生成預設建構函數
    Point() = default;
    
    Point(int px, int py) {
        x = px;
        y = py;
        cout << "帶參建構: Point(" << x << ", " << y << ")" << endl;
    }
};

int main() {
    Point p1;          // OK：使用編譯器生成的預設建構函數
    Point p2(3, 4);    // OK
    
    // 注意：p1.x 和 p1.y 仍然是未初始化的垃圾值！
    // 因為 = default 生成的建構函數和編譯器原本自動生成的行為一樣
    cout << "p1.x = " << p1.x << ", p1.y = " << p1.y << endl;  // 垃圾值
    
    return 0;
}
```

---

## 14.5 `= default` 與手動寫空建構函數的差異

這是一個微妙但重要的區別：

```cpp
#include <iostream>
using namespace std;

class A {
public:
    int value;
    A() = default;  // 編譯器生成的版本
};

class B {
public:
    int value;
    B() { }  // 使用者自己寫的空建構函數
};

int main() {
    // === 情境 1：一般宣告 ===
    A a1;    // value 是垃圾值（= default 不初始化基本型別）
    B b1;    // value 也是垃圾值（空建構函數也不初始化）
    
    // === 情境 2：值初始化（Value Initialization）===
    A a2{};  // value 被初始化為 0！
    B b2{};  // value 仍然是垃圾值！
    
    cout << "=== 一般宣告 ===" << endl;
    cout << "a1.value = " << a1.value << " (垃圾值)" << endl;
    cout << "b1.value = " << b1.value << " (垃圾值)" << endl;
    
    cout << "\n=== 值初始化 {} ===" << endl;
    cout << "a2.value = " << a2.value << " (應該是 0)" << endl;
    cout << "b2.value = " << b2.value << " (可能仍是垃圾值)" << endl;
    
    return 0;
}
```

### 預期輸出

```
=== 一般宣告 ===
a1.value = 32764 (垃圾值)
b1.value = 0 (垃圾值)

=== 值初始化 {} ===
a2.value = 0 (應該是 0)
b2.value = 0 (可能仍是垃圾值)
```

**差異解析**：

| 場景 | `= default` | 手動寫 `{ }` |
|------|-------------|--------------|
| `A a;` / `B b;` | 基本型別不初始化 | 基本型別不初始化 |
| `A a{};` / `B b{};` | **觸發值初始化**，基本型別歸零 | 只調用空建構函數，**不觸發值初始化** |
| 語義 | 這是一個**平凡的（trivial）**建構函數 | 這是一個**使用者定義的**建構函數 |

`= default` 保留了建構函數的「平凡性（triviality）」，這讓類別可以享受某些編譯器優化，也影響了值初始化的行為。這在進階場景（例如 `memcpy` 優化、POD 類型判斷）中很重要。

---

## 14.6 帶預設參數的建構函數也是預設建構函數

```cpp
#include <iostream>
using namespace std;

class Color {
private:
    int r, g, b;

public:
    // 所有參數都有預設值 → 這也是預設建構函數！
    Color(int red = 0, int green = 0, int blue = 0) {
        r = (red >= 0 && red <= 255) ? red : 0;
        g = (green >= 0 && green <= 255) ? green : 0;
        b = (blue >= 0 && blue <= 255) ? blue : 0;
    }

    void print() const {
        cout << "  RGB(" << r << ", " << g << ", " << b << ")" << endl;
    }
};

int main() {
    Color c1;               // 全部使用預設值 → (0, 0, 0)
    Color c2(255);           // green 和 blue 用預設值 → (255, 0, 0)
    Color c3(0, 128);        // blue 用預設值 → (0, 128, 0)
    Color c4(100, 200, 50);  // 全部指定
    
    cout << "c1: "; c1.print();   // 黑色
    cout << "c2: "; c2.print();   // 紅色
    cout << "c3: "; c3.print();   // 綠色
    cout << "c4: "; c4.print();   // 自定義
    
    return 0;
}
```

### 預期輸出

```
c1:   RGB(0, 0, 0)
c2:   RGB(255, 0, 0)
c3:   RGB(0, 128, 0)
c4:   RGB(100, 200, 50)
```

但要注意，**不能同時有無參建構函數和全預設參數建構函數**，否則會產生歧義：

```cpp
class Bad {
public:
    Bad() { }                    // 建構函數 A
    Bad(int x = 0) { }          // 建構函數 B（也是預設建構函數）
};

int main() {
    Bad b;  // 編譯錯誤！歧義：應該調用 A 還是 B？
    return 0;
}
```

---

## 14.7 預設建構函數與陣列

預設建構函數在使用**對象陣列**時非常重要：

```cpp
#include <iostream>
#include <string>
using namespace std;

class Enemy {
private:
    string type;
    int health;

public:
    // 必須有預設建構函數，否則無法創建陣列
    Enemy() {
        type = "小怪";
        health = 100;
    }
    
    Enemy(string t, int hp) {
        type = t;
        health = hp;
    }

    void print() const {
        cout << "  " << type << " (HP: " << health << ")" << endl;
    }
    
    void setType(string t) { type = t; }
    void setHealth(int hp) { health = hp; }
};

int main() {
    cout << "=== 對象陣列（需要預設建構函數）===" << endl;
    
    // 創建 5 個 Enemy，每個都調用預設建構函數
    Enemy enemies[5];
    
    for (int i = 0; i < 5; i++) {
        enemies[i].print();
    }
    
    cout << "\n=== 修改後 ===" << endl;
    enemies[0].setType("Boss");
    enemies[0].setHealth(5000);
    enemies[2].setType("精英怪");
    enemies[2].setHealth(500);
    
    for (int i = 0; i < 5; i++) {
        enemies[i].print();
    }
    
    return 0;
}
```

### 預期輸出

```
=== 對象陣列（需要預設建構函數）===
  小怪 (HP: 100)
  小怪 (HP: 100)
  小怪 (HP: 100)
  小怪 (HP: 100)
  小怪 (HP: 100)

=== 修改後 ===
  Boss (HP: 5000)
  小怪 (HP: 100)
  精英怪 (HP: 500)
  小怪 (HP: 100)
  小怪 (HP: 100)
```

**為什麼需要預設建構函數？** 因為 `Enemy enemies[5];` 要一次創建 5 個對象，但語法上沒有位置讓你傳參數給每一個元素，所以每個元素都必須用預設建構函數來初始化。

如果沒有預設建構函數：

```cpp
class NoDefault {
public:
    NoDefault(int x) { }  // 只有帶參建構函數
};

int main() {
    // NoDefault arr[3];   // 編譯錯誤！沒有預設建構函數！
    
    // 解決方法：用初始化列表逐一初始化
    NoDefault arr[3] = { NoDefault(1), NoDefault(2), NoDefault(3) };  // OK
    return 0;
}
```

---

## 14.8 `= delete`：明確禁止預設建構

有時候你**故意不想**讓對象在沒有參數的情況下被創建，可以用 `= delete`（C++11）：

```cpp
#include <iostream>
#include <string>
using namespace std;

class DatabaseConnection {
private:
    string host;
    int port;

public:
    // 明確禁止預設建構：沒有連接資訊就不能創建
    DatabaseConnection() = delete;
    
    DatabaseConnection(string h, int p) {
        host = h;
        port = p;
        cout << "連接到 " << host << ":" << port << endl;
    }

    void print() const {
        cout << "  資料庫連接: " << host << ":" << port << endl;
    }
};

int main() {
    // DatabaseConnection db;  // 編譯錯誤！預設建構函數被 delete 了
    // error: use of deleted function 'DatabaseConnection::DatabaseConnection()'
    
    DatabaseConnection db("localhost", 5432);  // OK
    db.print();
    
    return 0;
}
```

### 預期輸出

```
連接到 localhost:5432
  資料庫連接: localhost:5432
```

**使用場景**：當一個對象在沒有特定資訊的情況下不應該存在時，用 `= delete` 表達你的設計意圖。這比「忘記定義預設建構函數」更明確——它告訴閱讀程式碼的人：「我**故意**不允許預設建構。」

---

## 14.9 完整綜合範例

```cpp
#include <iostream>
#include <string>
using namespace std;

// ============================================================
// 範例 1：使用 = default
// ============================================================
class Config {
public:
    int width;
    int height;
    bool fullscreen;
    
    Config() = default;  // 請編譯器生成預設建構函數
    
    Config(int w, int h, bool fs) 
        : width(w), height(h), fullscreen(fs) { }
    
    void print() const {
        cout << "  " << width << "x" << height 
             << (fullscreen ? " [全螢幕]" : " [視窗]") << endl;
    }
};

// ============================================================
// 範例 2：全預設參數的建構函數
// ============================================================
class Timer {
private:
    int hours;
    int minutes;
    int seconds;

public:
    Timer(int h = 0, int m = 0, int s = 0) {
        hours = (h >= 0 && h < 24) ? h : 0;
        minutes = (m >= 0 && m < 60) ? m : 0;
        seconds = (s >= 0 && s < 60) ? s : 0;
    }
    
    void print() const {
        // 手動格式化為 HH:MM:SS
        cout << "  ";
        if (hours < 10) cout << "0";
        cout << hours << ":";
        if (minutes < 10) cout << "0";
        cout << minutes << ":";
        if (seconds < 10) cout << "0";
        cout << seconds << endl;
    }
};

// ============================================================
// 範例 3：= delete 禁止預設建構
// ============================================================
class FileHandle {
private:
    string filename;
    bool isOpen;

public:
    FileHandle() = delete;  // 沒有檔名就不能創建
    
    FileHandle(string fname) {
        filename = fname;
        isOpen = true;
        cout << "  打開檔案: " << filename << endl;
    }
    
    void print() const {
        cout << "  檔案: " << filename 
             << " [" << (isOpen ? "開啟" : "關閉") << "]" << endl;
    }
};

int main() {
    cout << "========================================" << endl;
    cout << "   第 14 課：預設建構函數 綜合範例" << endl;
    cout << "========================================" << endl;
    
    // --- Config：= default ---
    cout << "\n[1] Config (= default)" << endl;
    Config c1{};                         // 值初始化：全部歸零
    Config c2(1920, 1080, true);         // 帶參建構
    cout << "c1: "; c1.print();
    cout << "c2: "; c2.print();
    
    // --- Timer：全預設參數 ---
    cout << "\n[2] Timer (全預設參數)" << endl;
    Timer t1;                // 全部預設 → 00:00:00
    Timer t2(14);            // 只給小時 → 14:00:00
    Timer t3(8, 30);         // 給小時和分鐘 → 08:30:00
    Timer t4(23, 59, 59);   // 全部指定
    cout << "t1: "; t1.print();
    cout << "t2: "; t2.print();
    cout << "t3: "; t3.print();
    cout << "t4: "; t4.print();
    
    // --- Timer 陣列（因為有預設建構函數，所以可以） ---
    cout << "\n[3] Timer 陣列" << endl;
    Timer timers[3];  // 3 個 Timer 都用預設值
    for (int i = 0; i < 3; i++) {
        cout << "timers[" << i << "]: ";
        timers[i].print();
    }
    
    // --- FileHandle：= delete ---
    cout << "\n[4] FileHandle (= delete)" << endl;
    // FileHandle fh;  // 編譯錯誤！
    FileHandle f1("data.txt");
    FileHandle f2("config.json");
    f1.print();
    f2.print();
    
    return 0;
}
```

### 編譯與執行

```bash
g++ -std=c++17 -o lesson14 lesson14.cpp
./lesson14
```

### 預期輸出

```
========================================
   第 14 課：預設建構函數 綜合範例
========================================

[1] Config (= default)
c1:   0x0 [視窗]
c2:   1920x1080 [全螢幕]

[2] Timer (全預設參數)
t1:   00:00:00
t2:   14:00:00
t3:   08:30:00
t4:   23:59:59

[3] Timer 陣列
timers[0]:   00:00:00
timers[1]:   00:00:00
timers[2]:   00:00:00

[4] FileHandle (= delete)
  打開檔案: data.txt
  打開檔案: config.json
  檔案: data.txt [開啟]
  檔案: config.json [開啟]
```

---

## 14.10 本課重點回顧

| 概念 | 說明 |
|------|------|
| 預設建構函數 | 不需要參數就能調用的建構函數 |
| 編譯器自動生成 | 只有在你**完全沒有定義任何建構函數**時才會自動生成 |
| 自動生成的行為 | 不初始化基本型別，但會調用類別型別成員的建構函數 |
| `= default` | 明確要求編譯器生成預設建構函數，保留平凡性 |
| `= delete` | 明確禁止預設建構函數 |
| 全預設參數 | 所有參數都有預設值的建構函數也算預設建構函數 |
| 陣列需求 | 對象陣列 `T arr[N];` 需要預設建構函數 |
| 值初始化 | `T obj{};` 配合 `= default` 會將基本型別歸零 |

---

## 14.11 下一課預告

下一課我們將學習**帶參數的建構函數**的更多細節——包括參數傳遞方式的選擇（值傳遞 vs 引用傳遞 vs const 引用）、參數命名與成員同名的處理、以及預設參數的進階用法。

準備好進入 **第 15 課：帶參數的建構函數** 了嗎？
*/



#include <iostream>
#include <string>
#include <vector>
using namespace std;

// ============================================================
// 範例 1：使用 = default
// ============================================================
class Config {
public:
    int width;
    int height;
    bool fullscreen;
    
    Config() = default;  // 請編譯器生成預設建構函數
    
    Config(int w, int h, bool fs) 
        : width(w), height(h), fullscreen(fs) { }
    
    void print() const {
        cout << "  " << width << "x" << height 
             << (fullscreen ? " [全螢幕]" : " [視窗]") << endl;
    }
};

// ============================================================
// 範例 2：全預設參數的建構函數
// ============================================================
class Timer {
private:
    int hours;
    int minutes;
    int seconds;

public:
    Timer(int h = 0, int m = 0, int s = 0) {
        hours = (h >= 0 && h < 24) ? h : 0;
        minutes = (m >= 0 && m < 60) ? m : 0;
        seconds = (s >= 0 && s < 60) ? s : 0;
    }
    
    void print() const {
        // 手動格式化為 HH:MM:SS
        cout << "  ";
        if (hours < 10) cout << "0";
        cout << hours << ":";
        if (minutes < 10) cout << "0";
        cout << minutes << ":";
        if (seconds < 10) cout << "0";
        cout << seconds << endl;
    }
};

// ------------------------------------------------------------
// 對照組 A：= default + NSDMI —— 讓「無參建立」也保證有初值
//   Config 的 `= default` 不會初始化 width/height/fullscreen，
//   所以 `Config c;` 之後讀取它們是 UB。加上 NSDMI 之後，
//   不論 `ConfigSafe c;` 或 `ConfigSafe c{}` 都有確定的值。
// ------------------------------------------------------------
class ConfigSafe {
public:
    int  width      = 800;     // NSDMI：類別作者的保證，呼叫端無從搞砸
    int  height     = 600;
    bool fullscreen = false;

    ConfigSafe() = default;
    ConfigSafe(int w, int h, bool fs) : width(w), height(h), fullscreen(fs) {}

    void print() const {
        cout << "  " << width << "x" << height
             << (fullscreen ? " [全螢幕]" : " [視窗]") << endl;
    }
};

// ------------------------------------------------------------
// 對照組 B：clamp 取代歸零
//   Timer 對超範圍的值一律歸零：Timer(25, 70, 99) 變成 00:00:00。
//   「25 點」變成「0 點」在畫面上完全看不出異常，除錯時很難聯想。
//   clamp 到邊界（23:59:59）至少保留了「這個值太大」的線索。
// ------------------------------------------------------------
class TimerSafe {
public:
    TimerSafe(int h = 0, int m = 0, int s = 0)
        : hours(clampTo(h, 23)), minutes(clampTo(m, 59)), seconds(clampTo(s, 59)) {}

    void print() const {
        cout << "  ";
        if (hours < 10) cout << "0";
        cout << hours << ":";
        if (minutes < 10) cout << "0";
        cout << minutes << ":";
        if (seconds < 10) cout << "0";
        cout << seconds << endl;
    }

private:
    static int clampTo(int v, int hi) {
        if (v < 0)  return 0;
        if (v > hi) return hi;
        return v;
    }
    int hours;      // 宣告順序 = 初始化順序
    int minutes;
    int seconds;
};

// ============================================================
// 範例 3：= delete 禁止預設建構
// ============================================================
class FileHandle {
private:
    string filename;
    bool isOpen;

public:
    FileHandle() = delete;  // 沒有檔名就不能創建
    
    FileHandle(string fname) {
        filename = fname;
        isOpen = true;
        cout << "  打開檔案: " << filename << endl;
    }
    
    void print() const {
        cout << "  檔案: " << filename 
             << " [" << (isOpen ? "開啟" : "關閉") << "]" << endl;
    }
};

// -----------------------------------------------------------------------------
// 【日常實務範例】應用程式設定的三層合併（預設值 → 設定檔 → 環境變數）
//   情境：真實服務的設定幾乎都是分層疊加的：
//     (1) 程式內建的預設值（一定要有，且必須安全）
//     (2) 設定檔覆蓋其中一部分
//     (3) 環境變數再覆蓋（部署時臨時調整）
//   這正是本課三種手法的實戰匯集：
//     * NSDMI 提供第 (1) 層 —— 由類別作者保證，任何建構路徑都生效，
//       不像「值初始化」那樣要靠呼叫端記得寫大括號
//     * `= default` 讓「只要預設值」的呼叫端寫一行就好
//     * 每一層只覆蓋「有提供的欄位」，沒提供的自動沿用上一層
//   關鍵設計：預設值必須是「安全的那一邊」——workerThreads 預設 4 而非 0，
//   maxRequestMb 預設 10 而非無上限。忘記設定時系統仍能正常且安全地運作。
// -----------------------------------------------------------------------------
class AppSettings {
public:
    // 第 (1) 層：NSDMI 內建預設值 —— 類別作者的保證，呼叫端無從搞砸
    string host          = "0.0.0.0";
    int    port          = 8080;
    int    workerThreads = 4;        // 不是 0：0 個工作執行緒等於服務停擺
    int    maxRequestMb  = 10;       // 不是無上限：避免被超大請求打爆
    bool   enableMetrics = true;

    AppSettings() = default;         // 只要預設值時，這樣就夠了

    // 第 (2)(3) 層：只覆蓋「有提供」的欄位，其餘沿用既有值
    void applyOverride(const string& key, const string& value) {
        if (value.empty()) return;                       // 空值視為未提供
        if      (key == "host")          host = value;
        else if (key == "port")          port = toInt(value, port);
        else if (key == "workers")       workerThreads = toInt(value, workerThreads);
        else if (key == "max_request_mb") maxRequestMb = toInt(value, maxRequestMb);
        else if (key == "metrics")       enableMetrics = (value == "true" || value == "1");

        // 覆蓋之後仍要守住安全下限 —— 外部輸入永遠不可信任
        if (workerThreads < 1)  workerThreads = 1;
        if (maxRequestMb  < 1)  maxRequestMb  = 1;
        if (port < 1 || port > 65535) port = 8080;
    }

    void describe(const string& label) const {
        cout << "    " << label << ": " << host << ":" << port
             << "  workers=" << workerThreads
             << ", maxReq=" << maxRequestMb << "MB"
             << ", metrics=" << (enableMetrics ? "on" : "off") << endl;
    }

private:
    // 解析失敗就沿用原值，而不是變成 0 —— 靜默歸零是本課反覆強調的反面教材
    static int toInt(const string& s, int fallback) {
        try { return stoi(s); }
        catch (const exception&) { return fallback; }
    }
};

// -----------------------------------------------------------------------------
// 【LeetCode 實戰範例】LeetCode 155. Min Stack
//   題目：設計一個支援 push / pop / top / getMin 的堆疊，四個操作都要 O(1)。
//   為什麼用到本主題：題目給的簽名 MinStack() 就是一個**預設建構函數**——
//         「初始化這個堆疊物件」。它正好示範了本課最正面的一課：
//         當所有成員都是自己會初始化的型別（這裡是兩個 std::vector）時，
//         你**什麼都不必寫**，一行 = default 就夠了，
//         而且不會有任何「忘記初始化」的風險。
//         對照本課反覆出現的反面教材（int 成員沒有 NSDMI 就是不確定值），
//         這說明了「成員自己負責初始化」為什麼是最省事的設計。
//   關鍵想法：另開一個 minStack_，每次 push 都同步壓入「目前為止的最小值」，
//         使 getMin() 退化成一次 back()，達成 O(1)。
//   複雜度：四個操作皆為 O(1)；空間 O(n)。
// -----------------------------------------------------------------------------
class MinStack {
private:
    vector<int> data_;      // 兩個成員都是 vector，各自預設建構為空
    vector<int> minStack_;  // 與 data_ 等長，記錄「到此為止的最小值」

public:
    MinStack() = default;   // 成員都會自己初始化 → 這裡什麼都不必寫

    void push(int val) {
        data_.push_back(val);
        if (minStack_.empty() || val < minStack_.back()) minStack_.push_back(val);
        else                                             minStack_.push_back(minStack_.back());
    }

    void pop() {
        if (data_.empty()) return;
        data_.pop_back();
        minStack_.pop_back();
    }

    int  top()   const { return data_.back(); }
    int  getMin() const { return minStack_.back(); }
    bool empty() const { return data_.empty(); }
};

int main() {
    cout << "========================================" << endl;
    cout << "   第 14 課：預設建構函數 綜合範例" << endl;
    cout << "========================================" << endl;
    
    // --- Config：= default ---
    cout << "\n[1] Config (= default)" << endl;
    Config c1{};                         // 值初始化：全部歸零
    Config c2(1920, 1080, true);         // 帶參建構
    cout << "c1: "; c1.print();
    cout << "c2: "; c2.print();
    
    // --- Timer：全預設參數 ---
    cout << "\n[2] Timer (全預設參數)" << endl;
    Timer t1;                // 全部預設 → 00:00:00
    Timer t2(14);            // 只給小時 → 14:00:00
    Timer t3(8, 30);         // 給小時和分鐘 → 08:30:00
    Timer t4(23, 59, 59);   // 全部指定
    cout << "t1: "; t1.print();
    cout << "t2: "; t2.print();
    cout << "t3: "; t3.print();
    cout << "t4: "; t4.print();
    
    // --- Timer 陣列（因為有預設建構函數，所以可以） ---
    cout << "\n[3] Timer 陣列" << endl;
    Timer timers[3];  // 3 個 Timer 都用預設值
    for (int i = 0; i < 3; i++) {
        cout << "timers[" << i << "]: ";
        timers[i].print();
    }
    
    // --- FileHandle：= delete ---
    cout << "\n[4] FileHandle (= delete)" << endl;
    // FileHandle fh;  // 編譯錯誤！
    FileHandle f1("data.txt");
    FileHandle f2("config.json");
    f1.print();
    f2.print();

    // ─────────────────────────────────────────────────────────
    cout << "\n[5] = default 的隱藏風險：成員仍未被初始化" << endl;
    // Config c0;  cout << c0.width;   // ⚠️ UB：= default 不初始化內建型別成員
    cout << "  `Config c0; cout << c0.width;` 是 UB —— = default 不做初始化" << endl;
    Config valueInit{};                 // 值初始化：非 user-provided → 先零初始化
    cout << "  `Config c{};` 值初始化 -> ";
    valueInit.print();
    cout << "  ↑ 這個安全，但要靠呼叫端記得寫大括號，類別作者無法強制" << endl;

    ConfigSafe cs1;                     // NSDMI：類別作者的保證
    ConfigSafe cs2{};
    cout << "  ConfigSafe cs1;  -> "; cs1.print();
    cout << "  ConfigSafe cs2{}; -> "; cs2.print();
    cout << "  ↑ NSDMI 讓兩種寫法都安全 —— 這才是可靠的做法" << endl;

    // ─────────────────────────────────────────────────────────
    cout << "\n[6] 驗證策略對照：歸零 vs clamp" << endl;
    Timer bad(25, 70, 99);              // 全部超出範圍
    cout << "  Timer(25, 70, 99)      -> "; bad.print();
    cout << "     ↑ 全部歸零成 00:00:00，「25 點」變成「0 點」很難察覺" << endl;

    TimerSafe better(25, 70, 99);
    cout << "  TimerSafe(25, 70, 99)  -> "; better.print();
    cout << "     ↑ clamp 到 23:59:59，保留了「這是個過大的值」的線索" << endl;

    // ─────────────────────────────────────────────────────────
    cout << "\n[7] 實務：三種手法組合成一個 RAII 型別" << endl;
    vector<FileHandle> handles;
    handles.reserve(3);                 // reserve 不需要預設建構函式
    handles.emplace_back("access.log");
    handles.emplace_back("error.log");
    handles.emplace_back("audit.log");
    cout << "  用 emplace_back 建立了 " << handles.size() << " 個 handle:" << endl;
    for (const FileHandle& h : handles) h.print();
    // vector<FileHandle> bad2(3);      // ❌ 需要預設建構函式，已被 delete
    cout << "  （`vector<FileHandle> v(3);` 會編譯失敗 —— 正是 = delete 的目的）" << endl;

    // ─────────────────────────────────────────────────────────
    cout << "\n[8] 實務：設定的三層合併" << endl;
    AppSettings cfg;                                   // 第 (1) 層：NSDMI 預設值
    cfg.describe("內建預設值        ");

    // 第 (2) 層：設定檔只提供了兩個欄位
    cfg.applyOverride("port", "9090");
    cfg.applyOverride("workers", "16");
    cfg.describe("套用設定檔後      ");

    // 第 (3) 層：部署時用環境變數再覆蓋一個
    cfg.applyOverride("host", "127.0.0.1");
    cfg.describe("套用環境變數後    ");

    // 非法輸入一律被安全下限攔住，不會歸零或溢位
    AppSettings badCfg;
    badCfg.applyOverride("workers", "0");
    badCfg.applyOverride("port", "99999");
    badCfg.applyOverride("max_request_mb", "不是數字");
    badCfg.describe("非法輸入（已修正）");
    cout << "  ↑ NSDMI 保證「沒提供的欄位」一定有安全的值，" << endl;
    cout << "    而不是依賴呼叫端記得寫 `AppSettings cfg{};`。" << endl;

    // --- LeetCode 155. Min Stack ---
    cout << "\n[LeetCode 155] Min Stack（MinStack() 就是一個預設建構函數）" << endl;
    MinStack ms;
    cout << "  MinStack ms;  → empty = " << (ms.empty() ? "true" : "false")
         << "（兩個 vector 成員自己初始化為空，= default 就夠）" << endl;
    ms.push(-2); ms.push(0); ms.push(-3);
    cout << "  push(-2), push(0), push(-3)" << endl;
    cout << "  getMin() = " << ms.getMin() << "   (期望 -3)" << endl;
    ms.pop();
    cout << "  pop() 之後 top() = " << ms.top() << "   (期望 0)" << endl;
    cout << "  getMin() = " << ms.getMin() << "   (期望 -2)" << endl;

    return 0;
}

// 編譯: g++ -std=c++17 -Wall -Wextra "第 14 課：預設建構函數（Default Constructor）10.cpp" -o demo10
// 註：`= default` 與 `= delete` 需 C++11 以上。


// === 預期輸出 ===
// ========================================
//    第 14 課：預設建構函數 綜合範例
// ========================================
//
// [1] Config (= default)
// c1:   0x0 [視窗]
// c2:   1920x1080 [全螢幕]
//
// [2] Timer (全預設參數)
// t1:   00:00:00
// t2:   14:00:00
// t3:   08:30:00
// t4:   23:59:59
//
// [3] Timer 陣列
// timers[0]:   00:00:00
// timers[1]:   00:00:00
// timers[2]:   00:00:00
//
// [4] FileHandle (= delete)
//   打開檔案: data.txt
//   打開檔案: config.json
//   檔案: data.txt [開啟]
//   檔案: config.json [開啟]
//
// [5] = default 的隱藏風險：成員仍未被初始化
//   `Config c0; cout << c0.width;` 是 UB —— = default 不做初始化
//   `Config c{};` 值初始化 ->   0x0 [視窗]
//   ↑ 這個安全，但要靠呼叫端記得寫大括號，類別作者無法強制
//   ConfigSafe cs1;  ->   800x600 [視窗]
//   ConfigSafe cs2{}; ->   800x600 [視窗]
//   ↑ NSDMI 讓兩種寫法都安全 —— 這才是可靠的做法
//
// [6] 驗證策略對照：歸零 vs clamp
//   Timer(25, 70, 99)      ->   00:00:00
//      ↑ 全部歸零成 00:00:00，「25 點」變成「0 點」很難察覺
//   TimerSafe(25, 70, 99)  ->   23:59:59
//      ↑ clamp 到 23:59:59，保留了「這是個過大的值」的線索
//
// [7] 實務：三種手法組合成一個 RAII 型別
//   打開檔案: access.log
//   打開檔案: error.log
//   打開檔案: audit.log
//   用 emplace_back 建立了 3 個 handle:
//   檔案: access.log [開啟]
//   檔案: error.log [開啟]
//   檔案: audit.log [開啟]
//   （`vector<FileHandle> v(3);` 會編譯失敗 —— 正是 = delete 的目的）
//
// [8] 實務：設定的三層合併
//     內建預設值        : 0.0.0.0:8080  workers=4, maxReq=10MB, metrics=on
//     套用設定檔後      : 0.0.0.0:9090  workers=16, maxReq=10MB, metrics=on
//     套用環境變數後    : 127.0.0.1:9090  workers=16, maxReq=10MB, metrics=on
//     非法輸入（已修正）: 0.0.0.0:8080  workers=1, maxReq=10MB, metrics=on
//   ↑ NSDMI 保證「沒提供的欄位」一定有安全的值，
//     而不是依賴呼叫端記得寫 `AppSettings cfg{};`。
//
// [LeetCode 155] Min Stack（MinStack() 就是一個預設建構函數）
//   MinStack ms;  → empty = true（兩個 vector 成員自己初始化為空，= default 就夠）
//   push(-2), push(0), push(-3)
//   getMin() = -3   (期望 -3)
//   pop() 之後 top() = 0   (期望 0)
//   getMin() = -2   (期望 -2)
