#include <iostream>
#include <string>
using namespace std;

class AutoGenerated {
public:
    int number;        // 基本型別
    double value;      // 基本型別
    string text;       // 類別型別（string 有自己的預設建構函數）
    
    // 我們沒有定義任何建構函數
    // 編譯器會自動生成一個預設建構函數
    
    void print() const {
        cout << "number = " << number << endl;   // 未定義（垃圾值）
        cout << "value  = " << value << endl;    // 未定義（垃圾值）
        cout << "text   = [" << text << "]" << endl;  // 空字串（string 的預設建構）
    }
};

int main() {
    cout << "=== 編譯器自動生成的預設建構函數 ===" << endl;
    AutoGenerated obj;
    obj.print();
    
    return 0;
}
