// =============================================================================
//  第 14 課：預設建構函數 1  —  編譯器自動生成的 default constructor 做了什麼
// =============================================================================
//
// 【主題資訊 Information】
//   主題      : implicitly-declared / implicitly-defined default constructor
//   觸發條件  : 類別**完全沒有**使用者宣告的 constructor 時，編譯器才會自動生成
//   標準版本  : C++98 起；本檔用到的 <type_traits> 檢測工具是 C++11
//   標頭檔    : <iostream>、<string>、<type_traits>
//   關鍵結論  : 它不是「什麼都不做」，也不是「全部歸零」——而是「逐成員 default-init」
//
// 【詳細解釋 Explanation】
//
// 【1. 自動生成的 default constructor 究竟做了什麼】
//   它的定義非常精確：對每個非靜態資料成員執行 **default-initialization**。
//   而 default-initialization 對不同型別的意義完全不同：
//       * class type（string、vector、你自己寫的有 constructor 的類別）
//           → 呼叫該型別自己的 default constructor
//       * 內建型別（int、double、float、char、bool、指標）
//           → **不做任何事**，記憶體維持原樣，值不確定（indeterminate）
//       * 陣列
//           → 對每個元素套用上述規則
//   所以本檔的 AutoGenerated：text 保證是空字串，number 與 value 則不確定。
//   同一個物件裡有些成員安全、有些危險，這正是它難以察覺的原因。
//
// 【2. 「零開銷原則」是這個設計的唯一理由】
//   C++ 的信條是「不為你沒要求的東西付出代價」。若語言強制清零，
//   那麼 char buf[65536]; 這種成員每次建構都要付出 memset 的成本，
//   即使你下一行就要用 read() 整塊覆蓋掉。
//   C 也是同樣的哲學，C++ 只是把它延續下來。
//
// 【3. 它什麼時候「不會」被生成】
//   只要你宣告了**任何**一個 constructor（哪怕是帶三個參數的），
//   編譯器就不再自動生成 default constructor——這是第 14 課 2.cpp 的主題。
//   另外，若類別含有以下成員，自動生成的版本會被定義為 deleted：
//       * 沒有 default constructor 的 class type 成員
//       * const 成員且沒有 NSDMI（因為 const 物件必須初始化）
//       * reference 成員（reference 必須綁定對象）
//   此時寫 T obj; 會編譯失敗，錯誤訊息是「use of deleted function」。
//
// 【4. 三種一勞永逸的修法】
//   (a) NSDMI（C++11，最推薦）：int number = 0; 寫在宣告處，
//       之後不管新增幾個 constructor 都不會漏掉。
//   (b) 自己寫 constructor 並用成員初始化列表。
//   (c) 呼叫端寫 T obj{}; 值初始化——但這要靠呼叫端記得，類別作者無法強制。
//
// 【概念補充 Concept Deep Dive】
//   ▍implicitly-declared vs implicitly-defined
//     編譯器一開始只是「宣告」它；只有當程式真的用到（odr-used）時，
//     才會「定義」出實際的函式本體。所以一個從未被預設建構的類別，
//     它的 default constructor 可能根本不存在於產出的目的碼中。
//
//   ▍trivial default constructor
//     若自動生成的版本不需要做任何事（沒有 class type 成員、沒有 virtual、
//     沒有 NSDMI），它就是 trivial 的，編譯器可以完全不產生任何指令。
//     本檔用 std::is_trivially_default_constructible 實測驗證這一點。
//     AutoGenerated 因為含 std::string 所以不是 trivial；
//     但它的 int / double 成員**依然**不會被初始化——
//     「非 trivial」不等於「會幫你清零」，這是很多人搞混的地方。
//
//   ▍static storage duration 的例外
//     全域或 static 物件即使沒有初始化，也保證先被 zero-initialize。
//     所以 static AutoGenerated g; 的 number 是 0，而區域變數則不是。
//     本檔實測示範了這個差異。
//
// 【注意事項 Pay Attention】
//   1. 本檔輸出中 number / value 為不確定值，每次執行、每台機器都可能不同。
//   2. 讀取未初始化的內建型別成員是 UB，不可依賴任何觀察到的數值。
//   3. -Wall -Wextra 對這類「成員未初始化」通常不會警告，別指望編譯器攔你。
//   4. 全域／static 物件會被 zero-initialize，區域物件不會——不要用前者的
//      觀察結果推論後者。
//
// ═══════════════════════════════════════════════════════════════════════════
// 【面試題】編譯器生成的 default constructor
// ───────────────────────────────────────────────────────────────────────────
// 🔥 Q1. 編譯器自動生成的 default constructor 會把成員清成 0 嗎？
//     答：不會。它對每個成員做 default-initialization：class type 成員呼叫
//         自己的 default constructor（string → 空字串），內建型別成員
//         **完全不碰**，值不確定。它既不是「什麼都不做」，也不是「全部歸零」。
//     追問：那為什麼 static 或全域物件看起來是 0？→ 那是 static storage duration
//         的 zero-initialization 保證，跟 constructor 無關；區域物件沒有這個待遇。
//
// 🔥 Q2. 什麼情況下編譯器「不會」生成 default constructor？
//     答：(1) 你已經宣告了任何一個 constructor；
//         (2) 類別含有沒有 default constructor 的 class type 成員、
//             沒有 NSDMI 的 const 成員、或 reference 成員
//             —— 這些情況下自動生成的版本會被定義為 deleted。
//     追問：deleted 和「不存在」有差別嗎？→ 有。deleted 版本仍參與多載解析，
//         選中它才報錯（use of deleted function），錯誤訊息比較明確。
//
// ⚠️ 陷阱. 「這個類別含 std::string，所以它的 default constructor 不是 trivial，
//          那 int 成員應該也會被初始化吧？」
//     答：不會。trivial 與否描述的是「這個 constructor 需不需要做事」，
//         而不是「它會幫你把所有成員都設好」。含 string 只代表它必須呼叫
//         string 的 constructor，int 成員依然被原封不動地跳過。
//     為什麼會錯：把「非 trivial」誤解成「完整初始化」。
//         正確的心智模型是逐成員套規則，而不是整個物件一起處理。
// ═══════════════════════════════════════════════════════════════════════════

#include <iostream>
#include <string>
#include <type_traits>
using namespace std;

class AutoGenerated {
public:
    int number;        // 基本型別 → 不會被初始化
    double value;      // 基本型別 → 不會被初始化
    string text;       // 類別型別（string 有自己的預設建構函數）→ 保證是空字串

    // 我們沒有定義任何建構函數
    // 編譯器會自動生成一個預設建構函數

    void print() const {
        cout << "number = " << number << endl;   // 不確定值（讀取即 UB）
        cout << "value  = " << value << endl;    // 不確定值（讀取即 UB）
        cout << "text   = [" << text << "]" << endl;  // 空字串（string 的預設建構）
    }
};

// 修好的版本：NSDMI，一次寫好、永不遺漏
class FixedByNSDMI {
public:
    int    number = 0;
    double value  = 0.0;
    string text   = "(未設定)";

    void print() const {
        cout << "number = " << number << ", value = " << value
             << ", text = [" << text << "]" << endl;
    }
};

// 全域物件：static storage duration → 保證先被 zero-initialize
AutoGenerated gAuto;

// 編譯期事實查核（本機 GCC 15.2 實測）
static_assert(!std::is_trivially_default_constructible<AutoGenerated>::value,
              "含 std::string，所以整體不是 trivial —— 但 int/double 仍不會被初始化");
static_assert(std::is_trivially_default_constructible<int>::value,
              "int 的 default-initialization 不做任何事");

// -----------------------------------------------------------------------------
// 【LeetCode 實戰範例】從缺
//   理由：本檔談的是「編譯器生成的 default constructor 的精確語意」，
//         是語言規則層次的內容。LeetCode 的設計題都會自己寫 constructor，
//         從來不會依賴編譯器生成的版本，也觀察不到未初始化成員的行為。
//         本課真正對應的設計題（155 Min Stack、705 Design HashSet）
//         安排在 7.cpp、10.cpp 與 summary.cpp。
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// 【日常實務範例】統計計數器（Metrics）：漏掉初始化如何污染監控資料
//   情境：服務要回報「處理筆數 / 失敗筆數 / 累計延遲」。這種 struct 幾乎
//         一定是「宣告出來就開始 ++」，沒有人會特地寫 constructor。
//         一旦成員沒有 NSDMI，計數器就從一個不確定值開始累加——
//         監控圖表會出現天文數字或負值，而且完全無法重現。
//   正解：計數器型別的每個欄位都給 NSDMI，讓「歸零」成為型別的保證。
// -----------------------------------------------------------------------------
struct MetricsUnsafe {      // ❌ 沒有任何初始化保證
    long processed;
    long failed;
    double totalLatencyMs;
};

struct Metrics {            // ✅ NSDMI：一定從 0 開始
    long   processed      = 0;
    long   failed         = 0;
    double totalLatencyMs = 0.0;

    void record(bool ok, double latencyMs) {
        ++processed;
        if (!ok) ++failed;
        totalLatencyMs += latencyMs;
    }

    double avgLatencyMs() const {
        return processed == 0 ? 0.0 : totalLatencyMs / static_cast<double>(processed);
    }

    void report() const {
        cout << "  處理 " << processed << " 筆，失敗 " << failed
             << " 筆，平均延遲 " << avgLatencyMs() << " ms" << endl;
    }
};

int main() {
    cout << "=== 編譯器自動生成的預設建構函數（區域物件）===" << endl;
    AutoGenerated obj;
    obj.print();
    cout << "  ↑ text 保證為空字串；number / value 的值不確定，" << endl;
    cout << "    每次執行都可能不同，讀取它們本身就是 UB。" << endl;

    cout << "\n=== 同一個類別，但是全域物件 ===" << endl;
    gAuto.print();
    cout << "  ↑ 全域／static 物件有 zero-initialization 保證，所以是 0。" << endl;
    cout << "    這是 storage duration 的效果，不是 constructor 幫你做的。" << endl;

    cout << "\n=== 值初始化：呼叫端自保 ===" << endl;
    AutoGenerated vi{};      // AutoGenerated 沒有使用者宣告的 constructor → 歸零
    vi.print();

    cout << "\n=== 正解：NSDMI（類別作者負責）===" << endl;
    FixedByNSDMI fixed;
    fixed.print();
    cout << "  ↑ 不需要呼叫端配合，怎麼建構都是這個值" << endl;

    cout << "\n=== 日常實務：監控計數器 ===" << endl;
    Metrics m;               // 不必寫 constructor，NSDMI 已保證從 0 開始
    m.record(true,  12.5);
    m.record(true,   8.0);
    m.record(false, 45.5);
    m.report();
    cout << "  若改用 MetricsUnsafe，processed 會從一個不確定值開始累加，" << endl;
    cout << "  監控圖表可能出現天文數字或負值，且無法重現。" << endl;

    return 0;
}

// 編譯: g++ -std=c++17 -Wall -Wextra "第 14 課：預設建構函數（Default Constructor）1.cpp" -o def1

// === 預期輸出 ===
// ⚠️ 區域物件 obj 的 number / value 是不確定值（讀取即 UB），下方為某一次執行的結果，
//    每次執行都可能不同——本次 number 剛好是 0，這正是這個坑最危險的地方：
//    它常常「看起來正常」。全域物件、值初始化與 NSDMI 的結果才是有保證的。
// === 編譯器自動生成的預設建構函數（區域物件）===
// number = 0
// value  = 6.38726e-310
// text   = []
//   ↑ text 保證為空字串；number / value 的值不確定，
//     每次執行都可能不同，讀取它們本身就是 UB。
//
// === 同一個類別，但是全域物件 ===
// number = 0
// value  = 0
// text   = []
//   ↑ 全域／static 物件有 zero-initialization 保證，所以是 0。
//     這是 storage duration 的效果，不是 constructor 幫你做的。
//
// === 值初始化：呼叫端自保 ===
// number = 0
// value  = 0
// text   = []
//
// === 正解：NSDMI（類別作者負責）===
// number = 0, value = 0, text = [(未設定)]
//   ↑ 不需要呼叫端配合，怎麼建構都是這個值
//
// === 日常實務：監控計數器 ===
//   處理 3 筆，失敗 1 筆，平均延遲 22 ms
//   若改用 MetricsUnsafe，processed 會從一個不確定值開始累加，
//   監控圖表可能出現天文數字或負值，且無法重現。
